Replace deprecated wfGetDB & User::newFromId
hallowelt/mwstake-mediawiki-component-utils pull request #5
Opened 2024-04-08 10:16 UTC by HamishSlater

ERM36615

2024-12-03 06:11 UTC, DvogelHallowelt requested changes

2024-12-03 06:11 UTC, DvogelHallowelt commented on src/Utility/GroupHelper.php
> +		$dbr = $services->getDBLoadBalancer()->getConnection( DB_REPLICA );
Why do you not use the injected IDatabase object?

2024-12-03 06:11 UTC, DvogelHallowelt commented on src/Utility/GroupHelper.php
> +		$userFactory = $services->getUserFactory();
Wouldn't it be better to inject UserFactory?

2025-02-04 10:37 UTC, osnard approved these changes

2025-02-04 10:37 UTC, merged